mv_booking_homepage:
    path:     /{_locale}/home
    defaults: { _controller: MVBookingBundle:Booking:index, _locale: fr }
    requirements:
        _locale: fr|en
    
mv_booking_date:
    path:     /{_locale}/date
    defaults: { _controller: MVBookingBundle:Booking:translation, _locale: fr}
    requirements:
        _locale: fr|en

mv_booking_checkdate:
    path:     /checkdate
    defaults: { _controller: MVBookingBundle:Booking:checkDate}

mv_booking_howmany:
    path:     /{_locale}/{date}/howmany
    defaults: { _controller: MVBookingBundle:Booking:howMany}
    requirements:
        _locale: fr|en

mv_booking_users:
    path:     /{_locale}/{date}/{nbr}/users
    defaults: { _controller: MVBookingBundle:Booking:addUser}
    requirements:
        _locale: fr|en
        nbr    : \d{1}

mv_booking_check:
    path:     /{_locale}/{date}/{nbr}/check
    defaults: { _controller: MVBookingBundle:Booking:checkOrder}
    requirements:
        _locale: fr|en
        nbr    : \d{1}

mv_booking_stripe:
    path:     /{_locale}/{amount}/{date}/paiement
    defaults: { _controller: MVBookingBundle:Booking:stripe}
    requirements:
        _locale: fr|en

mv_booking_confirmation:
    path:     /{_locale}/confirmation
    defaults: { _controller: MVBookingBundle:Booking:confirmationOrder}
    requirements:
        _locale: fr|en

mv_booking_deleteuser:
    path:     /delete/{id}/{date}/{nbr}
    defaults: { _controller: MVBookingBundle:Booking:deleteUser}
    requirements:
        id: \d+
        nbr: \d{1}

mv_booking_cancel:
    path:     /{_locale}/{sessionId}/cancel
    defaults: { _controller: MVBookingBundle:Booking:cancelOrder}