mv_booking_homepage:
    path:     /{_locale}/home
    defaults: { _controller: MVBookingBundle:Booking:index, _locale: fr }
    requirements:
        _locale: fr|en
    

mv_booking_date:
    path:     /{_locale}/date
    defaults: { _controller: MVBookingBundle:Booking:translation, _locale: fr}
    requirements:
        _locale: fr|en
