services:

    mv_booking.stripe:
        class: MV\BookingBundle\Stripe\MVStripe
        arguments:
            - "@mv_booking.mail"
            - "%locale%"
            - eur
        public: true

    mv_booking.mail:
        class: MV\BookingBundle\Email\MVMail
        arguments:
            - "@mailer"
            - "@twig"
        public: true

    mv_booking.session:
        class: MV\BookingBundle\Session\MVSession
        public: true

    mv_booking.checksessiondate:
        class: MV\BookingBundle\CheckSessionDate\MVSessionDate
        public: true

    mv_booking.createOrder:
        class: MV\BookingBundle\Order\MVCreateOrder
        public: true

    mv_booking_checkCost:
        class: MV\BookingBundle\Cost\MVCheckCost
        public: true

    mv_booking_purge:
        class: MV\BookingBundle\Purge\MVPurgeUser
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"

  
