mv_booking:
    resource: "@MVBookingBundle/Resources/config/routing.yml"
    prefix:   /

mv_core:
    resource: "@MVCoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

