<?php

namespace MV\BookingBundle\Repository;

/**
 * BasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketRepository extends \Doctrine\ORM\EntityRepository
{
    

    public function selectUsersTicketId($sessionId)
    {
        $qb = $this->createQueryBuilder('t');
        $qb
            -> innerJoin('t.user', 't')
            -> addSelect('t');
        $qb
            -> where('ut = t.')
            -> setParameter('sessionId', $sessionId);

        return $qb  
            ->getQuery()
            ->getResult();
    }

}
