<?php

namespace MV\BookingBundle\Repository;

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends \Doctrine\ORM\EntityRepository
{
    public function selectId($sessionId)
    {
        $qb = $this->createQueryBuilder('c');
        $qb
            -> select('c.id')
            -> where('c.specialKey = :sessionId')
            -> setParameter('sessionId', $sessionId);

        $id = $qb->getQuery()->getSingleResult();
        return $id;
    }

    public function aloneUsers()
    {
        $qb = $this->createQueryBuilder('c');
        $qb
            ->leftJoin('command_user', 'cu')
            ->addSelect('cu')
            ->select('cu.userId');


        $listAloneUser = $qb->getQuery()
            ->getResult();

        return $listAloneUser;
    }
}
