<?php

namespace MV\BookingBundle\Repository;

use Doctrine\ORM\QueryBuilder;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function selectUserOrder($sessionId)
    {
        $qb = $this->createQueryBuilder('u');
        $qb 
            -> where('u.sessionKey = :sessionId')
            -> setParameter('sessionId', $sessionId);

        $listActiveUsers = $qb->getQuery()
                              ->getResult();

        return $listActiveUsers;     
    }

    public function countUserDay($date)
    {
        $qb = $this->createQueryBuilder('u');
        $qb
            -> select($qb->expr()->count('u.id'))
            -> where('u.date = :date')
            -> setParameter('date', $date);

        $listVisitors = $qb->getQuery()
                           ->getSingleScalarResult();

        return $listVisitors;
            
    }

    public function findAloneUser()
    {
        $qb = $this->createQueryBuilder('u');
        $qb
            ->select('u')
            ->leftJoin('u.command', 'uc')
            ->addSelect('uc')
            ->where($qb->expr()->isNull('uc'));

        $listAloneUser = $qb->getQuery()
            ->getResult();

        return $listAloneUser;
    }
}
